# Stores constants for the program

TYPE_MAX_LEN = 8
NUMBER_LEN = 9
NAME_MIN_LEN = 1
NAME_MAX_LEN = 25
STREET_ADDRESS_MIN_LEN = 1
STREET_ADDRESS_MAX_LEN = 25
CITY_MIN_LEN = 1
CITY_MAX_LEN = 14
STATE_LEN = 2
ZIP_CODE_LEN = 5

SERVICE_CODE_LEN = 6
SERVICE_NAME_MIN_LEN = 1
SERVICE_NAME_MAX_LEN = 20
SERVICE_FEE_MAX = 999.99

COMMENT_MAX_LEN = 100